<a href="https://colab.research.google.com/github/nannthd/bsc_dpdm22/blob/main/Performance_Evaluation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [43]:
from sklearn import datasets 
iris_data = datasets.load_iris()

In [44]:
X = iris_data['data']
y = iris_data['target']

In [45]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, KFold

In [46]:
# Define the decision tree model
model = DecisionTreeClassifier()

# Define the cross-validation method กำหนดวิธีการตรวจสอบความถูกต้องโดยใช้ 10-fold cross-validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Perform k-fold cross-validation and return the accuracy scores
scores = cross_val_score(model, X, y, cv=kf)

# Print the mean accuracy score and standard deviation
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.95 (+/- 0.12)

In [47]:
# Define the decision tree model
model = DecisionTreeClassifier(max_depth=2)

# Define the cross-validation method
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Perform k-fold cross-validation and return the accuracy scores
scores = cross_val_score(model, X, y, cv=kf)

# Print the mean accuracy score and standard deviation
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.95 (+/- 0.12)

In [48]:
from sklearn.model_selection import LeaveOneOut

In [49]:
# Define the decision tree model
dt = DecisionTreeClassifier()

# Define the cross-validation method (leave-one-out) กำหนดวิธีการตรวจสอบความถูกต้องโดยใช้ leave-one-out
loo = LeaveOneOut()

# Perform leave-one-out cross-validation and return the accuracy scores
scores = cross_val_score(dt, X, y, cv=loo)

# Print the mean accuracy score and standard deviation
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))

Accuracy: 0.95 (+/- 0.42)

In [50]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

 transform numpy array to dataframe

In [51]:
import pandas as pd
import numpy as np

In [52]:
columns = iris_data['feature_names']
X_df = pd.DataFrame(X, columns=columns)
X_df

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [53]:
X_df['label']=y #เพิ่มคำตอบจะได้ดูออกตอน shuffle
X_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2
149,5.9,3.0,5.1,1.8,2

In [54]:
# shuffle the rows of the DataFrame
shuffled_df = X_df.sample(frac=1, random_state=6) #random_state เพื่อให้การสุ่มแต่ละครั้งเหมือนกัน/เหมือนเดิม
shuffled_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
4,5.0,3.6,1.4,0.2,0
116,6.5,3.0,5.5,1.8,2
2,4.7,3.2,1.3,0.2,0
23,5.1,3.3,1.7,0.5,0
123,6.3,2.7,4.9,1.8,2
...,...,...,...,...,...
148,6.2,3.4,5.4,2.3,2
79,5.7,2.6,3.5,1.0,1
109,7.2,3.6,6.1,2.5,2
106,4.9,2.5,4.5,1.7,2
138,6.0,3.0,4.8,1.8,2

In [55]:
shuffled_df['fold']=15*[1,2,3,4,5,6,7,8,9,10]
shuffled_df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label,fold
4,5.0,3.6,1.4,0.2,0,1
116,6.5,3.0,5.5,1.8,2,2
2,4.7,3.2,1.3,0.2,0,3
23,5.1,3.3,1.7,0.5,0,4
123,6.3,2.7,4.9,1.8,2,5
...,...,...,...,...,...,...
148,6.2,3.4,5.4,2.3,2,6
79,5.7,2.6,3.5,1.0,1,7
109,7.2,3.6,6.1,2.5,2,8
106,4.9,2.5,4.5,1.7,2,9
138,6.0,3.0,4.8,1.8,2,10

#HW6 วนลูปทำ 10-fold cross validation

In [56]:
# Define the number of folds
#n_folds = 10

# Split the data into features and target
#X = shuffled_df.drop('label', axis=1)
#y = shuffled_df['label']

# Define a cross-validation object with the specified number of folds
#kfold = KFold(n_splits=n_folds)

# Loop over the folds
#for fold, (train_idx, test_idx) in enumerate(kfold.split(X, y)):
    # Get the training and testing data for the current fold
    #X_train, y_train = X.iloc[train_idx], y.iloc[train_idx]
    #X_test, y_test = X.iloc[test_idx], y.iloc[test_idx]
    
    # Create a decision tree classifier object
    #model = DecisionTreeClassifier()
    
    # Fit the model on the training data
    #model.fit(X_train, y_train)
    
    # Evaluate the model on the testing data
    #scores = cross_val_score(model, X_test, y_test, cv=kfold)
    
    # Print the cross-validation score and the data for the current fold
    #print(f"Fold: {fold+1}")
    #print("Mean accuracy: %0.2f (+/- %0.2f)" % (np.mean(scores), np.std(scores) * 2))
    #print(shuffled_df[shuffled_df['fold'] == fold+1])
    #rint()

## เฉลย HW6

In [69]:
from sklearn.metrics import accuracy_score

In [78]:
test_fold = 1 # เอาตัวที่1มาเป็นtest

test_data = shuffled_df[shuffled_df['fold']==test_fold]
training_data = shuffled_df[shuffled_df['fold']!=test_fold] # เอาที่เหลือเป็นtrain

In [79]:
test_data.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label,fold
4,5.0,3.6,1.4,0.2,0,1
127,6.1,3.0,4.9,1.8,2,1
37,4.9,3.6,1.4,0.1,0,1
45,4.8,3.0,1.4,0.3,0,1
17,5.1,3.5,1.4,0.3,0,1

In [80]:
X_test = test_data.iloc[:,:-2]
y_test = test_data.iloc[:,-2]
X_train = training_data.iloc[:,:-2]
y_train = training_data.iloc[:,-2]

In [81]:
model = DecisionTreeClassifier(max_depth=2)

model.fit(X_train,y_train)

y_predict = model.predict(X_test)

In [82]:
acc = accuracy_score(y_test,y_predict)
print(f'accuracy of fold {test_fold} = {acc}')

accuracy of fold 1 = 0.8666666666666667

In [77]:
acc_fold=[] #สร้างlistมาเก็บไว้ใช้ต่อ
for test_fold in range(1,11):
    test_data = shuffled_df[shuffled_df['fold']==test_fold]
    training_data = shuffled_df[shuffled_df['fold']!=test_fold]

    X_test = test_data.iloc[:,:-2]
    y_test = test_data.iloc[:,-2]
    X_train = training_data.iloc[:,:-2]
    y_train = training_data.iloc[:,-2]

    model = DecisionTreeClassifier(max_depth=2)
    model.fit(X_train,y_train)
    y_predict = model.predict(X_test)

    acc = accuracy_score(y_test,y_predict)
    print(f'accuracy of fold {test_fold} = {acc}')
    acc_fold.append(acc)

print(f'\naverage accuracy = {np.mean(acc)}')

accuracy of fold 1 = 0.8666666666666667
accuracy of fold 2 = 1.0
accuracy of fold 3 = 0.9333333333333333
accuracy of fold 4 = 1.0
accuracy of fold 5 = 0.9333333333333333
accuracy of fold 6 = 0.9333333333333333
accuracy of fold 7 = 0.9333333333333333
accuracy of fold 8 = 1.0
accuracy of fold 9 = 0.8666666666666667
accuracy of fold 10 = 0.9333333333333333

average accuracy = 0.9333333333333333

# add Precision & Recall from ChatGPT

In [83]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import precision_score, recall_score

# Load the iris dataset
iris = load_iris()

# Define the decision tree model
model = DecisionTreeClassifier()

# Define the k-fold cross validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Train and evaluate the model using 10-fold cross validation
precision_scores = []
recall_scores = []
for train_idx, test_idx in kf.split(iris.data, iris.target):
    # Get the training and testing data for this fold
    X_train, y_train = iris.data[train_idx], iris.target[train_idx]
    X_test, y_test = iris.data[test_idx], iris.target[test_idx]

    # Train the model on the training data for this fold
    model.fit(X_train, y_train)

    # Predict the labels for the testing data for this fold
    y_pred = model.predict(X_test)

    # Calculate the precision and recall for this fold
    precision = precision_score(y_test, y_pred, average='macro')
    recall = recall_score(y_test, y_pred, average='macro')

    # Add the precision and recall scores to the lists for all folds
    precision_scores.append(precision)
    recall_scores.append(recall)

# Print the average precision and recall scores across all folds
print("Average precision score: %0.2f" % (sum(precision_scores) / len(precision_scores)))
print("Average recall score: %0.2f" % (sum(recall_scores) / len(recall_scores)))

Average precision score: 0.96
Average recall score: 0.96